### ISSUE TITLE
Some files truncate into buffer

### ISSUE THREAD

**Issue by cdenneen** [aurora/rmate#9] opened 2013-02-08 16:54 UTC
<pre>
user@host:~$ head -5 /etc/hosts
#
# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
# Use is subject to license terms.
#
# Internet host table
</pre>

<pre>
user@host:~$ sudo /tmp/rmate-new.bash /etc/hosts
</pre>

Buffer opens with only:

<pre>
#
# Copyrigh
</pre>

**Comment by scher200** [comment] 2016-10-19 06:50
+1 half of the file as result on the serverside

**Comment by aurora** [comment] 2016-10-20 10:07
@scher200 do you mean, you have this issue as well? Which system is it this happens on? I wasn't able to reproduce this behavior on any of my systems, so far ...

**Comment by scher200** [comment] 2016-10-20 12:50
@aurora yes, I have this issue as well,
Ubuntu 14.04 (mint 17 xfce)

I viewed the code but was amazed it is so short. Could it have something to do with: the # character?
Bot of my half empty files contain this character multiple times.

**Comment by Jammizzle** [comment] 2017-12-08 10:01
Not sure it's to do with the '#' character as I'm able to open my `my.cnf` which is full of them as they're used as comments. Possibly a different issue

**Comment by aurora** [comment] 2018-01-04 04:05
I just fixed issue #65, wrong detection of filesize. I wonder if this could be the same issue as what is reported in here. So if anybody of you is still following this, i would be really happy if you could download rmate from master branch and try it again. Thanks!

**Comment by aurora** [comment] 2018-01-09 15:23
I am closing this, because there's no feedback and i cannot reproduce the issue.

**Closed by aurora** 2018-01-09 15:23 UTC
Labels: bug
